version: "3"

services:

  nginx:
    network_mode: host
    image: nginx:latest
    volumes:
      - /home/docker-nginx-test/config/vhost_wp.conf:/etc/nginx/conf.d/vhost_wp.conf
    ports:
      - "8500:80"
    expose:
      - 8500
    restart: always
