version: "3"
services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - port_db_change:3306
    environment:
      MARIADB_ROOT_PASSWORD: password_wordpress_change_root
      MARIADB_DATABASE: db_port_db_change
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: password_wordpress_change

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "port_wordpress_change:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password_wordpress_change
      WORDPRESS_DB_NAME: db_port_db_change
volumes:
  db_data: {}
  wordpress_data: {}