version: "3"

services:

  nginx:
    network_mode: host
    image: nginx:latest
    volumes:
      - ./config/domain_wordpress_change.conf:/etc/nginx/conf.d/domain_wordpress_change.conf
    ports:
      - "port_wordpress_change:80"
    expose:
      - port_wordpress_change
    restart: always
