version: "3.8"
services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mysecret_live
      MARIADB_DATABASE: wordpress_db
      MARIADB_USER: user_wordpress
      MARIADB_PASSWORD: password_wordpress_change

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "port_wordpress_change:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user_wordpress
      WORDPRESS_DB_PASSWORD: password_wordpress_change
      WORDPRESS_DB_NAME: wordpress_db
volumes:
  db_data: {}
  wordpress_data: {}
